# script.py.mako
# Alembic revision script template

"""Schema from models.py - 20250808_235148

Revision ID: 2ae56f7da426
Revises: 8e28d38de16a
Create Date: 2025-08-08 21:51:49.173449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae56f7da426'
down_revision = '8e28d38de16a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'day_categories', ['name'])
    op.create_unique_constraint(None, 'food_categories', ['name'])
    op.create_unique_constraint(None, 'payment_methods', ['code'])
    op.create_unique_constraint(None, 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'payment_methods', type_='unique')
    op.drop_constraint(None, 'food_categories', type_='unique')
    op.drop_constraint(None, 'day_categories', type_='unique')
    # ### end Alembic commands ###